const english = {
  open: 'Open OpsFloa Assistant',
  title: 'OpsFloa Assistant',
  subtitle: 'Ask about work or open a page',
  close: 'Close assistant',
  newChat: 'Start a new conversation',
  welcome: 'What can I help you find in OpsFloa?',
  privacy: 'Answers use only data you can already see. Any available change requires your confirmation.',
  placeholder: 'Ask OpsFloa...',
  send: 'Send',
  thinking: 'Checking OpsFloa...',
  failed: 'I could not reach the assistant. Please try again.',
  tooLong: 'Keep requests under 2,000 characters.',
  confirm: 'Confirm',
  cancel: 'Cancel',
  working: 'Applying change...',
  completed: 'Completed',
  canceled: 'Canceled',
  actionFailed: 'The change could not be completed. Nothing else was changed.',
  approvedCount: '{n} approved.',
  skippedLockedCount: '{n} skipped because the pay period is locked.',
  prompts: ['What needs attention?', 'Show active projects', 'Take me to approvals'],
};

const spanish = {
  open: 'Abrir el Asistente de OpsFloa',
  title: 'Asistente de OpsFloa',
  subtitle: 'Pregunte sobre el trabajo o abra una pagina',
  close: 'Cerrar asistente',
  newChat: 'Iniciar una nueva conversacion',
  welcome: 'En que puedo ayudarle dentro de OpsFloa?',
  privacy: 'Las respuestas solo usan datos que usted puede ver. Cada cambio disponible requiere su confirmacion.',
  placeholder: 'Pregunte a OpsFloa...',
  send: 'Enviar',
  thinking: 'Revisando OpsFloa...',
  failed: 'No pude comunicarme con el asistente. Intentelo de nuevo.',
  tooLong: 'Mantenga la solicitud por debajo de 2,000 caracteres.',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
  working: 'Aplicando cambio...',
  completed: 'Completado',
  canceled: 'Cancelado',
  actionFailed: 'No se pudo completar el cambio. No se cambio nada mas.',
  approvedCount: '{n} aprobados.',
  skippedLockedCount: '{n} omitidos porque el periodo de pago esta bloqueado.',
  prompts: ['Que necesita atencion?', 'Mostrar proyectos activos', 'Llevame a aprobaciones'],
};

export function assistantStrings(language) {
  return String(language || '').toLowerCase().startsWith('span') ? spanish : english;
}
